export enum CarsManagerActions {
  CARS_MANAGER_CHANGE_ID = "CARS_MANAGER_CHANGE_ID",
  CARS_MANAGER_CHANGE_DATA = "CARS_MANAGER_CHANGE_DATA",
  CARS_MANAGER_ERROR = "CARS_MANAGER_ERROR",
  CARS_MANAGER_SET_DEFAULT = "CARS_MANAGER_SET_DEFAULT",
}
