export enum CategoryManagerActions {
  CATEGORY_MANAGER_CHANGE_ID = "CATEGORY_MANAGER_CHANGE_ID",
  CATEGORY_MANAGER_CHANGE_DATA = "CATEGORY_MANAGER_CHANGE_DATA",
  CATEGORY_MANAGER_ERROR = "CATEGORY_MANAGER_ERROR",
}
