export enum OrdersManagerActions {
  ORDERS_MANAGER_CHANGE_ID = "ORDERS_MANAGER_CHANGE_ID",
  ORDERS_MANAGER_CHANGE_DATA = "ORDERS_MANAGER_CHANGE_DATA",
  ORDERS_MANAGER_ERROR = "ORDERS_MANAGER_ERROR",
}
