export enum AuthorizationActions {
  AUTHORIZATION_LOGIN = "AUTHORIZATION_LOGIN",
  AUTHORIZATION_CHANGE_MAIL = "AUTHORIZATION_CHANGE_MAIL",
  AUTHORIZATION_CHANGE_PASSWORD = "AUTHORIZATION_CHANGE_PASSWORD",
}
