export enum CarsActions {
  CARS_INIT = "CARS_INIT",
  CARS_SET_FILTER = "CARS_SET_FILTER",
  CARS_INIT_FILTERED = "CARS_INIT_FILTERED",
  CARS_ERROR = "CARS_ERROR",
  CARS_DROP_FILTERED_DATA = "CARS_DROP_FILTERED_DATA",
  CARS_DEFAULT = "CARS_DEFAULT",
}
